version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "

  - package-ecosystem: "github-actions"
    target-branch: v1.6.1
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: "
    groups:
      github_actions:
        patterns:
          - "*"
    labels:
      - v1.6.1
